"""Test inputs + helpers for ``diffusion/`` modules.

``diffusion/`` 章的固定测试输入。
"""
from __future__ import annotations

import math
import os

import torch

from runtime.checks import (  # noqa: F401
    controlled_execution,
    controlled_forward,
    test_module_forward,
    test_module_method,
    test_module_shape,
)


CONTROL_FOLDER = os.path.dirname(os.path.abspath(__file__))


# Small constants for diffusion-side blocks.
N_batch = 1
N_token = 6
N_sample = 1
c_a     = 24
c_s     = 24
c_z     = 12
n_heads = 4
n_blocks = 2


def _ramp(shape: tuple, idx: int) -> torch.Tensor:
    lo = -2.0 - idx / 5
    hi = +2.0 + idx / 5
    n = math.prod(shape)
    return torch.linspace(lo, hi, n).reshape(shape).double()


feature_shapes = {
    "a":  (N_sample, N_token, c_a),
    "s":  (N_sample, N_token, c_s),
    "z":  (N_sample, N_token, N_token, c_z),
}
test_inputs = {name: _ramp(shape, i) for i, (name, shape) in enumerate(feature_shapes.items())}


# ----- Geometry helpers (Algorithms 19 + 29) -------------------------------
# Geometry test inputs are independent of the Transformer ones above.
# 几何 helper 的测试输入与上面的 Transformer 输入相互独立。
#
# IMPORTANT: ``frame_atoms`` must NOT be generated by a monotonic ramp.
# A ramp produces near-collinear (a, b, c) triples → w1 + w2 ≈ 0 inside
# ``expressCoordinatesInFrame``, and ``F.normalize(..., eps=1e-8)`` then
# returns an essentially arbitrary direction (numerically unstable, not
# bit-reproducible across BLAS backends).
# 用一段单调 ramp 生成会让三个原子近共线，导致 w1+w2≈0、F.normalize
# 退化、跨后端不可重现。改用 fixed-seed Gaussian，三个 3D 随机 frame
# 共线概率 ≈0。
N_atom_geo  = 7
N_frame_geo = 3
test_inputs["coords"]      = _ramp((N_atom_geo, 3), 4)
_g_geo = torch.Generator().manual_seed(0)
test_inputs["frame_atoms"] = (
    torch.randn((N_frame_geo, 3, 3), generator=_g_geo, dtype=torch.float64) * 2.0
    + torch.tensor([1.0, 0.5, -0.5], dtype=torch.float64)  # shift each frame off origin
)

# Masked, *batched* centre_random_augmentation input (Algorithm 19 mask branch).
# Two batch rows with different masks force the [..., 3] / [..., 1] broadcast
# that the masked-centering denominator must get right.
# 带 mask 的批量输入：两行不同 mask，强制走 [...,3]/[...,1] 广播。
_g_mask = torch.Generator().manual_seed(1)
test_inputs["coords_masked"] = torch.randn(
    (2, N_atom_geo, 3), generator=_g_mask, dtype=torch.float64
) * 3.0 + 5.0  # off-origin so centering is non-trivial
test_inputs["coords_mask"] = torch.tensor(
    [[1, 1, 1, 1, 1, 0, 0],
     [1, 1, 0, 1, 0, 1, 1]], dtype=torch.float64
)
